version: "3.7"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-network
  container:
    stdin_open: true
    tty: true
    image: ${container_name}
    container_name: ${container_name}
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./app/:/app/
    ports:
      - "8080:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge